// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/3/2025, 4:43:26 PM
const configMerger = require("/Users/zayn/Desktop/projects/arcihve/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/zayn/Desktop/projects/arcihve/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zayn/Desktop/projects/arcihve/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zayn/Desktop/projects/arcihve/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zayn/Desktop/projects/arcihve/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zayn/Desktop/projects/arcihve/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zayn/Desktop/projects/arcihve/plugins/**/*.{js,ts,mjs}","/Users/zayn/Desktop/projects/arcihve/composables/**/*.{js,ts,mjs}","/Users/zayn/Desktop/projects/arcihve/utils/**/*.{js,ts,mjs}","/Users/zayn/Desktop/projects/arcihve/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/zayn/Desktop/projects/arcihve/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/zayn/Desktop/projects/arcihve/app.config.{js,ts,mjs}"] }));

module.exports = config
